   <div id="home-wrap" class="clearfix">
            <div class="grid-loader"><i class="icon-spinner icon-spin"></i></div>
         <div id="wpex-grid-wrap">





<article class="post-33 post type-post status-publish format-standard hentry category-celebs tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry container">  
            <a href="#" title="Interview with a Rockstar" class="loop-entry-img-link">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/photodune-1405937-young-girl-with-a-guitar-m-440x659.jpg" alt="Interview with a Rockstar" />
            <div class="entry-overlay"><span class="icon-plus"></span></div>
        </a>
            <h2><a href="#" title="Interview with a Rockstar">Interview with a Rockstar</a></h2>
        <div class="entry-text">
            <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non? Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
           <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="#comments" class="comments-link"  title="Comment on Interview with a Rockstar">3 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-33" title="Like this"><span class="zilla-likes-count">36</span> <span class="zilla-likes-postfix"></span></a></li>           </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->

 
<article class="post-164 post type-post status-publish format-image hentry category-fashion tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry container">  
                <a href="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/zblack-and-white.jpg" title="Keep It Simple With Black &amp; White" class="loop-entry-img-link fancybox">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/zblack-and-white-440x537.jpg" alt="Keep It Simple With Black &amp; White" />
            <div class="entry-overlay"><span class="icon-fullscreen"></span></div>
        </a>
            <h2><a href="#" title="Keep It Simple With Black &amp; White">Keep It Simple With Black &amp; White</a></h2>
        <div class="entry-text">
             <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
             <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="##comments" class="comments-link"  title="Comment on Keep It Simple With Black &amp; White">3 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-164" title="Like this"><span class="zilla-likes-count">37</span> <span class="zilla-likes-postfix"></span></a></li>          </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->
 
<article class="post-22 post type-post status-publish format-gallery hentry category-fashion tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos loop-entry grid-4 container clearfix">  
                <a href="#" title="Hot Fall Trends!" class="loop-entry-img-link">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/photodune-2271303-pure-sexy-m-440x292.jpg" alt="Hot Fall Trends!" />
            <div class="entry-overlay"><span class="icon-picture"></span></div>
        </a>
            <h2><a href="#" title="Hot Fall Trends!">Hot Fall Trends!</a></h2>
        <div class="entry-text">
             <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
             <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="##comments" class="comments-link"  title="Comment on Hot Fall Trends!">4 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-22" title="Like this"><span class="zilla-likes-count">20</span> <span class="zilla-likes-postfix"></span></a></li>           </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->

 
<article class="post-148 post type-post status-publish format-standard hentry category-beauty tag-art tag-fashion-2 tag-make-up tag-models tag-music tag-photos tag-products tag-reviews loop-entry container">  
            <a href="#" title="Try These Hair Products Now" class="loop-entry-img-link">
            <img src="http://demoswpex.wpengine.netdna-cdn.com/fashionista/wp-content/uploads/sites/14/2012/09/zphotodune-3007452-luxory-brownhaired-model-m-440x293.jpg" alt="Try These Hair Products Now" />
            <div class="entry-overlay"><span class="icon-plus"></span></div>
        </a>
            <h2><a href="#" title="Try These Hair Products Now">Try These Hair Products Now</a></h2>
        <div class="entry-text">
            <p>Morbi vulputate egestas sem, eu cursus ligula ullamcorper non. Curabitur tristique velit eu mauris venenatis egestas. Phasellus bibendum placerat metus, sed molestie magna semper eget&#8230;.</p>
           <ul class="loop-entry-meta clearfix">
                <li class="meta-date"><span class="icon-calendar"></span>September 18, 2012</li>    
                                    <li class="meta-comments"><span class="icon-comment"></span> <a href="##comments" class="comments-link"  title="Comment on Try These Hair Products Now">3 comments</a></li>
                                <li class="meta-zilla-likes"><a href="index.html#" class="zilla-likes" id="zilla-likes-148" title="Like this"><span class="zilla-likes-count">15</span> <span class="zilla-likes-postfix"></span></a></li>          </ul> <!-- /loop-entry-meta -->
        </div><!-- /entry-text -->
    </article><!-- /entry -->

            </div><!-- /wpex-grid-wrap -->
                        <div class="infinite-scroll-nav clr"><div class="alignleft newer-posts"></div><div class="alignright older-posts"><a href="/page/2" >Older Posts &rarr;</a></div></div> </div><!-- /home-wrap -->
    
<div class="clear"></div>
</div><!-- /main-content -->
</div><!-- /wrap -->