<div id="sidr-close"><a href="#sidr-close" class="toggle-sidr-close"></a></div>
<a href="#sidr" class="mobile-menu-toggle"><span class="icon-reorder"></span>Browse<span class="icon-caret-down"></span></a>

<nav id="navigation" class="clearfix">
        <div class="menu-main-menu-container">
                <ul id="menu-main-menu" class="sf-menu">
                        <li id="menu-item-332" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-332">
                                <a href="#">Home</a>
                        </li>
                        <li id="menu-item-367" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-367"><a href="#">Menu 2</a></li>

<li id="menu-item-333" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-333"><a href="#">Categories</a>
<ul class="sub-menu">
        <li id="menu-item-334" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-334">
                <a href="#">Fashion</a>
        </li>
        </ul>
</li>

<li id="menu-item-369" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-369"><a href="#">About Me</a></li>
<li id="menu-item-368" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-368"><a href="#">Contact</a></li>
</ul>
</div>                        
<form method="get" id="searchbar" action="#">
<input type="search" name="s" id="search" value="Search..." onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;">
<input type="submit" id="searchsubmit" value="" />
</form> </nav>